### ISSUE TITLE
TypeError exception in PVSlicer when issubclass function is called

### ISSUE THREAD

**Issue by lpda** [radio-astro-tools/pvextractor#111]
I am trying to use PVSlicer as explained in https://pvextractor.readthedocs.io/en/latest/gui.html and I get the following error:

```
>>> from pvextractor.gui import PVSlicer
>>> pv = PVSlicer('cube.fits')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/.local/lib/python3.8/site-packages/pvextractor/gui.py", line 234, in wrapper
    return func(self, *args, **kwargs)
  File "~/.local/lib/python3.8/site-packages/pvextractor/gui.py", line 242, in wrapper
    return func(self, *args, **kwargs)
  File "~/.local/lib/python3.8/site-packages/pvextractor/gui.py", line 254, in __init__
    if hasattr(filename_or_cube, 'filled_data') or issubclass(filename_or_cube, BaseSpectralCube):
TypeError: issubclass() arg 1 must be a class
```

I think that modifying the line 254 of gui.py to be as follows would solve the issue:
```
    if hasattr(filename_or_cube, 'filled_data') or isinstance(filename_or_cube, BaseSpectralCube):
```

**Comment by lpda** [comment]
I have created the pull request #112 with the proposed solution.
