### ISSUE TITLE
Problem with example script

### ISSUE THREAD

**Issue by keflavich** [radio-astro-tools/pvextractor#62]
A user reported the following error when running the example notebook:
```
Traceback (most recent call last):
  File "pvextract.py", line 31, in <module>
    pv = extract_pv_slice(hdu, xy)
  File "/usr/local/lib/python2.7/dist-packages/pvextractor-0.0.dev225-py2.7.egg/pvextractor/pvextractor.py", line 103, in extract_pv_slice
    header = slice_wcs(wcs, spatial_scale=world_spacing).to_header()
  File "/usr/local/lib/python2.7/dist-packages/pvextractor-0.0.dev225-py2.7.egg/pvextractor/utils/wcs_slicing.py", line 31, in slice_wcs
    wcs_slice.wcs.crpix[0] = 1.
astropy.wcs._wcs.SingularMatrixError: ERROR 3 in wcsset() at line 1873 of file cextern/wcslib/C/wcs.c:
Linear transformation matrix is singular.
ERROR 3 in linset() at line 467 of file cextern/wcslib/C/lin.c:
PCi_ja matrix is singular.
```

I can't reproduce this.  I don't know why.

**Comment by teodam** [comment]
Hello,
I have the same error when I use the example script :
```
def load_wcs_from_file(filename):
    # Load the FITS hdulist using astropy.io.fits
    hdulist = fits.open(filename)

    # Parse the WCS keywords in the primary HDU
    w = wcs.WCS(hdulist[0].header)

    # Print out the "name" of the WCS, as defined in the FITS header
    print(w.wcs.name)

    # Print out all of the settings that were parsed from the header
    w.wcs.print_contents()

    # Some pixel coordinates of interest.
    pixcrd = numpy.array([[0, 0], [24, 38], [45, 98]], numpy.float_)

    # Convert pixel coordinates to world coordinates
    # The second argument is "origin" -- in this case we're declaring we
    # have 1-based (Fortran-like) coordinates.
    world = w.wcs_pix2world(pixcrd, 1)
    print(world)

    # Convert the same coordinates back to pixel coordinates.
    pixcrd2 = w.wcs_world2pix(world, 1)
    print(pixcrd2)

    # These should be the same as the original pixel coordinates, modulo
    # some floating-point error.
    assert numpy.max(numpy.abs(pixcrd - pixcrd2)) < 1e-6
```
This is my error :
```
WARNING: VerifyWarning: Invalid 'BLANK' keyword in header.  The 'BLANK' keyword is only applicable to integer data, and will be ignored in this HDU. [astropy.io.fits.hdu.image]
WARNING: FITSFixedWarning: 'celfix' made the change 'Linear transformation matrix is singular'. [astropy.wcs.wcs]
Traceback (most recent call last):
  File "/home/teodori/Bureau/Projet/main.py", line 48, in <module>
    load_wcs_from_file(filepath)
  File "/home/teodori/Bureau/Projet/main.py", line 16, in load_wcs_from_file
    w = wcs.WCS(hdulist[0].header)
  File "/usr/local/lib/python3.4/dist-packages/astropy/wcs/wcs.py", line 500, in __init__
    self.wcs.set()
astropy.wcs._wcs.SingularMatrixError: ERROR 3 in wcsset() at line 2213 of file cextern/wcslib/C/wcs.c:
Linear transformation matrix is singular.
ERROR 3 in linset() at line 607 of file cextern/wcslib/C/lin.c:
PCi_ja matrix is singular.
```
This is the picture i used : 
[image.zip](https://github.com/radio-astro-tools/pvextractor/files/307342/image.zip)

I'm using Python 3.4.3

Thanks
