### ISSUE TITLE
GUI crashes with Mac canvas?

### ISSUE THREAD

**Issue by keflavich** [radio-astro-tools/pvextractor#65]
Traceback:

```
Traceback (most recent call last):
  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 1936, in motion_notify_event
    self.callbacks.process(s, event)
  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/matplotlib/cbook.py", line 540, in process
    proxy(*args, **kwargs)
  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/matplotlib/cbook.py", line 415, in __call__
    return mtd(*args, **kwargs)
  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/pvextractor-0.0.dev233-py2.7.egg/pvextractor/gui.py", line 157, in on_motion
    canvas.restore_region(self.background)
AttributeError: 'FigureCanvasMac' object has no attribute 'restore_region'
```

**Comment by astrofrog** [comment]
Yes, this is expected at the moment but would be good to have a workaround (basically can't blit on OSX backend, so have to re-draw every time - gonna be slow!)

**Comment by keflavich** [comment]
Closing this as.... I don't know if mac canvases exist any more, but I don't have one.
