### ISSUE TITLE
Failure if spectral-cube is not installed

### ISSUE THREAD

**Issue by astrofrog** [radio-astro-tools/pvextractor#94]
If I run:

```python
import numpy as np
from pvextractor import Path, extract_pv_slice

p = Path([(1., 2.), (4., 2.), (5., 3.)])
cube = np.random.random((10, 11, 12))
extract_pv_slice(cube, path=p, wcs=None, order=0)
```

Then I get the following error on Python 3.7:

```
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    extract_pv_slice(cube, path=p, wcs=None, order=0)
  File "/home/tom/python/dev/lib/python3.7/site-packages/pvextractor/pvextractor.py", line 69, in extract_pv_slice
    if _is_spectral_cube(cube):
  File "/home/tom/python/dev/lib/python3.7/site-packages/pvextractor/pvextractor.py", line 116, in _is_spectral_cube
    if 'SpectralCube' in (obj.__class__):
TypeError: argument of type 'type' is not iterable
```

We should make sure that ``pvextractor`` continues to work if spectral-cube is not installed (maybe this should be a CI config)

**Comment by keflavich** [comment]
I'm also OK with declaring `spectral-cube` a required package.

**Comment by keflavich** [comment]
spectral-cube is now listed under install-requires
