### ISSUE TITLE
Can't pip install pvextractor

### ISSUE THREAD

**Issue by djeff1887** [radio-astro-tools/pvextractor#98]
PyDS9 and spectral-cube are already installed. When running `pip install https://github.com/radio-astro-tools/pvextractor/archive/master.zip`, I get the following output and error : 

Defaulting to user installation because normal site-packages is not writeable
Collecting https://github.com/radio-astro-tools/pvextractor/archive/master.zip
  Using cached https://github.com/radio-astro-tools/pvextractor/archive/master.zip
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /apps/python/3.7/bin/python3.7 /apps/python/3.7/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpk34g0yru
         cwd: /tmp/pip-req-build-lrc36bz2
    Complete output (36 lines):
    Traceback (most recent call last):
      File "/apps/python/3.7/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
        main()
      File "/apps/python/3.7/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/apps/python/3.7/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 133, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/tmp/pip-build-env-fgng28e4/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 161, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "/tmp/pip-build-env-fgng28e4/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 145, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 78, in <module>
        'write_to_template': VERSION_TEMPLATE})
      File "/tmp/pip-build-env-fgng28e4/overlay/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/apps/python/3.7/lib/python3.7/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/tmp/pip-build-env-fgng28e4/overlay/lib/python3.7/site-packages/setuptools/dist.py", line 424, in __init__
        k: v for k, v in attrs.items()
      File "/apps/python/3.7/lib/python3.7/distutils/dist.py", line 292, in __init__
        self.finalize_options()
      File "/tmp/pip-build-env-fgng28e4/overlay/lib/python3.7/site-packages/setuptools/dist.py", line 695, in finalize_options
        ep(self)
      File "/tmp/pip-build-env-fgng28e4/overlay/lib/python3.7/site-packages/setuptools/dist.py", line 702, in _finalize_setup_keywords
        ep.load()(self, ep.name, value)
      File "/tmp/pip-build-env-fgng28e4/overlay/lib/python3.7/site-packages/setuptools_scm/integration.py", line 17, in version_keyword
        dist.metadata.version = _get_version(config)
      File "/tmp/pip-build-env-fgng28e4/overlay/lib/python3.7/site-packages/setuptools_scm/__init__.py", line 148, in _get_version
        parsed_version = _do_parse(config)
      File "/tmp/pip-build-env-fgng28e4/overlay/lib/python3.7/site-packages/setuptools_scm/__init__.py", line 118, in _do_parse
        "use git+https://github.com/user/proj.git#egg=proj" % config.absolute_root
    LookupError: setuptools-scm was unable to detect version for '/tmp/pip-req-build-lrc36bz2'.

    Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

    For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
    ----------------------------------------
ERROR: Command errored out with exit status 1: /apps/python/3.7/bin/python3.7 /apps/python/3.7/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpk34g0yru Check the logs for full command output.

**Comment by astrofrog** [comment]
Could you try the suggestion in the error message to use pip install git+https://...?

**Comment by djeff1887** [comment]
Yes, it returns a different error. I ran `pip install git+https://github.com/radio-astro-tools/pvextractor/archive/master.zip --log ~/debuggingpippvextractor.txt` since it doesn't give a traceback in-terminal:

```
Traceback (most recent call last):                                                                                                                             
  File "/home/d.jeff/anaconda3/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 228, in _main                                              
    status = self.run(options, args)                                                                                                                           
  File "/home/d.jeff/anaconda3/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 182, in wrapper                                             
    return func(self, options, args)                                                                                                                           
  File "/home/d.jeff/anaconda3/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 324, in run                                                
    reqs, check_supported_wheels=not options.target_dir                                                                                                        
  File "/home/d.jeff/anaconda3/lib/python3.7/site-packages/pip/_internal/resolution/legacy/resolver.py", line 183, in resolve                                  
    discovered_reqs.extend(self._resolve_one(requirement_set, req))                                                                                            
  File "/home/d.jeff/anaconda3/lib/python3.7/site-packages/pip/_internal/resolution/legacy/resolver.py", line 388, in _resolve_one                             
    abstract_dist = self._get_abstract_dist_for(req_to_install)                                                                                                
  File "/home/d.jeff/anaconda3/lib/python3.7/site-packages/pip/_internal/resolution/legacy/resolver.py", line 340, in _get_abstract_dist_for                   
    abstract_dist = self.preparer.prepare_linked_requirement(req)                                                                                              
  File "/home/d.jeff/anaconda3/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 469, in prepare_linked_requirement                       
    hashes=self._get_linked_req_hashes(req)                                                                                                                    
  File "/home/d.jeff/anaconda3/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 239, in unpack_url                                       
    unpack_vcs_link(link, location)                                                                                                                            
  File "/home/d.jeff/anaconda3/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 99, in unpack_vcs_link                                   
    vcs_backend.unpack(location, url=hide_url(link.url))                                                                                                       
  File "/home/d.jeff/anaconda3/lib/python3.7/site-packages/pip/_internal/vcs/versioncontrol.py", line 733, in unpack                                           
    self.obtain(location, url=url)                                                                                                                             
  File "/home/d.jeff/anaconda3/lib/python3.7/site-packages/pip/_internal/vcs/versioncontrol.py", line 641, in obtain                                           
    self.fetch_new(dest, url, rev_options)                                                                                                                     
  File "/home/d.jeff/anaconda3/lib/python3.7/site-packages/pip/_internal/vcs/git.py", line 230, in fetch_new                                                   
    self.run_command(make_command('clone', '-q', url, dest))                                                                                                   
  File "/home/d.jeff/anaconda3/lib/python3.7/site-packages/pip/_internal/vcs/versioncontrol.py", line 774, in run_command                                      
    log_failed_cmd=log_failed_cmd)                                                                                                                             
  File "/home/d.jeff/anaconda3/lib/python3.7/site-packages/pip/_internal/vcs/versioncontrol.py", line 166, in call_subprocess                                  
    raise SubProcessError(exc_msg)                                                                                                                             
pip._internal.exceptions.SubProcessError: Command errored out with exit status 128: git clone -q https://github.com/radio-astro-tools/pvextractor/archive/master.zip /tmp/pip-req-build-plel7fi6 Check the logs for full command output.
```
Not sure if this will be helpful, but I'm using pip version 20.2.3.

**Comment by astrofrog** [comment]
@djeff1887 - can you try:

```
pip install git+https://github.com/radio-astro-tools/pvextractor
```

Thanks!

**Comment by djeff1887** [comment]
That totally worked, thanks so much!
